#Minecraft server properties

# customisable
motd=My RLCraft Parasited Server
view-distance=10
max-players=20
pvp=true
white-list=false
hardcore=false
# alternative: RTG
level-type=DEFAULT
level-name=world
level-seed=
# false = don't force players to be logged into mc accounts - will not display skins correctly
online-mode=true

# needed for RLCraft
difficulty=3
max-tick-time=-1
enable-command-block=true
allow-flight=true

# whatever
gamemode=0
spawn-protection=0
spawn-monsters=true
spawn-npcs=true
spawn-animals=true
allow-nether=true
generate-structures=true
generator-settings=
max-build-height=256
max-world-size=29999984
resource-pack-sha1=
resource-pack=
texture-pack=
force-gamemode=false
broadcast-console-to-ops=true
op-permission-level=4
enable-query=false
player-idle-timeout=0
snooper-enabled=false
network-compression-threshold=256
server-port=25565
server-ip=
hellworld=true
prevent-proxy-connections=false
use-native-transport=true
enable-rcon=false
